### ISSUE TITLE
mopidy/c/add failing on TypeError: add() got an unexpected keyword argument 'uri'

### ISSUE THREAD

**Issue by arthurlutz** [odiroot/mopidy-mqtt#2]
```
2020-05-25 23:28:41,830 INFO [732:Core-7] pykka: Exception returned from Core (urn:uuid:9ea0aa6b-83e6-471c-ba32-f46f8d597a7b) to caller:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
TypeError: add() got an unexpected keyword argument 'uri'
```

Trying to load a playlist using : 

```
mosquitto_pub -t 'mopidy/c/add' -m 'local:playlists/1.m3u8'    
```
Trying with `loa` stops the current music 

```
mosquitto_pub -t 'mopidy/c/loa' -m 'local:playlists/1.m3u8'    
```

**Comment by odiroot** [comment]
It seems Mopidy changed the Core API a bit: https://docs.mopidy.com/en/latest/api/core/#mopidy.core.TracklistController.add

I need to update my code. Thanks for the report.
